swagger: "2.0"
info:
  description: "This project proposes the creation of an online ordering system for a restaurant."
  version: "1.0.0"
  title: "Delilah Restó"
  contact:
    email: "nicolaszuleta95@gmail.com"
tags:
  - name: "users"
    description: "Operaciones con los usuarios"
  - name: "dishes"
    description: "Operaciones con los platos"
  - name: "orders"
    description: "Operaciones con los pedidos"
schemes:
- "https"
- "http"
paths:
  /user:
    post:
      tags:
      - "users"
      summary: "registrar un nuevo usuario"
      description: ""
      operationId: "newUser"
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto propietario para asignar a un edificio"
        required: true
        schema:
          $ref: "#/definitions/users"
      responses:
        "200":
          description: "user registered successfully"
        "400":
          description: "Invalid input"
  /dish:
    get:
      tags:
      - "dishes"
      summary: "Listar todos los platos"
      description: ""
      operationId: "getDishes"
      responses:
        "200":
          description: "returned dishes successfully"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/dishes'
        "404":
          description: "Not Found"
definitions:
  users:
    type: "object"
    properties:
      user_id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      fullname:
        type: "string"
      email:
        type: "string"
      address:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userType:
        type: "boolean"
        description: "columna para determinar si el usuario es Admin o no"
    xml:
      name: "users"
  dishes:
    type: "object"
    properties:
      dish_id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      price:
        type: "number"
      description:
        type: "string"
      category:
        type: "string"
      photo:
        type: "string"
    xml:
      name: "dishes"
  orders:
    type: "object"
    properties:
      order_id:
        type: "integer"
        format: "int64"
      user_id:
        type: "integer"
        format: "int64"
      date:
        type: "string"
        format: "date"
      total:
        type: "number"
      state:
        type: "string"
      address:
        type: "string"
      pay_type:
        type: "string"
    xml:
      name: "orders"
  items:
    type: "object"
    properties:
      item_id:
        type: "integer"
        format: "int64"
      order_id:
        type: "integer"
        format: "int64"
      dish_id:
        type: "integer"
        format: "int64"
      price:
        type: "number"
      quantity:
        type: "integer"
        format: "int32"
    xml:
      name: "items"
  favs:
    type: "object"
    properties:
      user_id:
        type: "integer"
        format: "int64"
      dish_id:
        type: "integer"
        format: "int64"
    xml:
      name: "favs"